# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-09-08 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_show', '0003_auto_20210908_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='w', max_length=255, null=True)),
                ('body', models.TextField(blank=True, default='w', null=True)),
            ],
        ),
    ]
